### ISSUE TITLE
xtcocotools version 

### ISSUE THREAD

**Issue by scfrank** [flyinglynx/CapeFormer#4]
I got an error setting up this project until I specified `xtcocotools==1.12`.

The current version (1.14.3) is incompatible with the required numpy:
```  
Traceback (most recent call last):
  File "__init__.cython-30.pxd", line 984, in numpy.import_array
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf . Check the section C-API incompatibility at the Troubleshooting ImportError section at https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility for indications on how to solve this problem .
...
File "/home/it4i-stfr/stella-scratch/.conda/envs/capeformer/lib/python3.8/site-packages/mmpose/datasets/datasets/base/kpt_2d_sview_rgb_img_bottom_up_dataset.py", line 8, in <module>
    from xtcocotools.coco import COCO
  File "/home/it4i-stfr/stella-scratch/.conda/envs/capeformer/lib/python3.8/site-packages/xtcocotools/coco.py", line 58, in <module>
    from . import mask as maskUtils
  File "/home/it4i-stfr/stella-scratch/.conda/envs/capeformer/lib/python3.8/site-packages/xtcocotools/mask.py", line 3, in <module>
    import xtcocotools._mask as _mask
  File "xtcocotools/_mask.pyx", line 23, in init xtcocotools._mask
File "__init__.cython-30.pxd", line 986, in numpy.import_array
ImportError: numpy.core.multiarray failed to import
```

**Comment by pegasus2004** [comment]
Have you resolved? It seems that we need a newer numpy, but my scipy wants numpy<1.23
